### ISSUE TITLE
npm ERR! 404  'crao@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by jod35** [Baronsindo/create-react-app-offline#1]
While running ` crao -n simple ` I got `crao command not found `.  Running `crao -n simple ` worked at first. The second time, I got the following error. 
`$ npx crao -n simpleapp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/crao - Not found
npm ERR! 404 
npm ERR! 404  'crao@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`
I need help.

**Comment by Baronsindo** [comment]
Hi try this command first

Npm  install -g create-react-app-offline

Then

crao -n <app-name>
